import { WorkspaceState } from './workspace';
export const DEMO_STATE: WorkspaceState = {
  leads: [
    {
      id: '1',
      name: 'Sarah Chen',
      email: 'sarah@northstar.example',
      company: 'Northstar Studio',
      title: 'Head of Operations',
      status: 'Qualified',
      industry: 'Design & creative',
      confidence: 92,
    },
    {
      id: '2',
      name: 'James Wilson',
      email: 'james@relay.example',
      company: 'Relay Technologies',
      title: 'VP of Sales',
      status: 'Contacted',
      industry: 'Software',
      confidence: 88,
    },
    {
      id: '3',
      name: 'Aisha Khan',
      email: 'aisha@bloom.example',
      company: 'Bloom Commerce',
      title: 'Founder',
      status: 'New',
      industry: 'E-commerce',
      confidence: 0,
    },
    {
      id: '4',
      name: 'Daniel Park',
      email: 'daniel@orbit.example',
      company: 'Orbit Labs',
      title: 'Co-founder',
      status: 'Meeting booked',
      industry: 'Software',
      confidence: 95,
    },
    {
      id: '5',
      name: 'Emma Davis',
      email: 'emma@forma.example',
      company: 'Forma Collective',
      title: 'Managing Director',
      status: 'New',
      industry: 'Consulting',
      confidence: 0,
    },
    {
      id: '6',
      name: 'Omar Hassan',
      email: 'omar@atlas.example',
      company: 'Atlas Digital',
      title: 'Sales Director',
      status: 'Replied',
      industry: 'Marketing',
      confidence: 86,
    },
  ],
  campaigns: [
    {
      id: '1',
      name: 'A better workflow for growing teams',
      audience: 'Software & creative agencies',
      status: 'Active',
      tone: 'Friendly',
      offer: 'Automate reporting so your team can focus on clients.',
      ids: ['1', '2', '3', '4'],
      sent: 2,
      replies: 1,
    },
    {
      id: '2',
      name: 'More conversations, less admin',
      audience: 'Sales leaders at digital companies',
      status: 'Draft',
      tone: 'Professional',
      offer: 'Bring outreach and customer conversations into one workspace.',
      ids: ['5', '6'],
      sent: 0,
      replies: 0,
    },
  ],
  drafts: [],
  meetings: [
    {
      id: '1',
      lead: '4',
      date: '2026-10-12',
      time: '14:30',
      duration: '30',
      status: 'Scheduled',
    },
  ],
  messages: [
    {
      lead: '1',
      type: 'Interested',
      text: 'Hi Bilal, this sounds relevant to what we are working on. Could we find 20 minutes next week to talk through the workflow?',
      replies: [],
    },
    {
      lead: '6',
      type: 'Question',
      text: 'Thanks for reaching out. How would this work with our existing sales process? Do you support a review step before emails are sent?',
      replies: [],
    },
  ],
  settings: {
    company: 'Bilal Studio',
    sender: 'Bilal Malik',
    offer: 'Help growing teams automate repetitive reporting and sales administration.',
    timezone: 'Asia/Karachi',
    limit: 50,
  },
  activity: [],
};
