"""complete sales workflow entities

Revision ID: 002
Revises: 001
Create Date: 2026-10-09 22:59:53.581599

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("audience", sa.String(length=500), nullable=False),
        sa.Column("offer", sa.Text(), nullable=False),
        sa.Column("tone", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_campaigns_status"), ["status"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_available_at"), ["available_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "workspace_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("sender", sa.String(length=200), nullable=False),
        sa.Column("offer", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("daily_limit", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaign_leads",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("campaign_id", "lead_id"),
    )
    op.create_table(
        "meetings",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("sync_status", sa.String(length=30), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("provider_event_id", sa.String(length=300), nullable=True),
        sa.Column("join_url", sa.String(length=1000), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_meetings_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_meetings_start_at"), ["start_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_meetings_status"), ["status"], unique=False)

    op.create_table(
        "workflow_runs",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_runs_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_status"), ["status"], unique=False)

    op.create_table(
        "email_drafts",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=True),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("approved_revision", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("queued_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("provider_message_id", sa.String(length=300), nullable=True),
        sa.Column("failure", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflow_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    with op.batch_alter_table("email_drafts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_drafts_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_email_drafts_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_email_drafts_status"), ["status"], unique=False)

    op.create_table(
        "followups",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["draft_id"], ["email_drafts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("followups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_followups_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_followups_lead_id"), ["lead_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_followups_status"), ["status"], unique=False)

    op.create_table(
        "messages",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=True),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("intent", sa.String(length=30), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["draft_id"], ["email_drafts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_lead_id"), ["lead_id"], unique=False)

    op.create_table(
        "webhook_events",
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["draft_id"], ["email_drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("linkedin_url", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("confidence", sa.Float(), server_default="0", nullable=False))
        batch_op.add_column(sa.Column("research", sa.JSON(), nullable=True))

    op.create_index("uq_leads_email_lower", "leads", [sa.text("lower(email)")], unique=True)
    op.bulk_insert(
        sa.table(
            "workspace_settings",
            sa.column("id", sa.Integer()),
            sa.column("company", sa.String()),
            sa.column("sender", sa.String()),
            sa.column("offer", sa.Text()),
            sa.column("timezone", sa.String()),
            sa.column("daily_limit", sa.Integer()),
        ),
        [
            {
                "id": 1,
                "company": "Salesway",
                "sender": "Salesway Team",
                "offer": "Help teams simplify sales administration.",
                "timezone": "Asia/Karachi",
                "daily_limit": 50,
            }
        ],
    )


def downgrade() -> None:
    op.drop_index("uq_leads_email_lower", table_name="leads")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_column("research")
        batch_op.drop_column("confidence")
        batch_op.drop_column("linkedin_url")

    op.drop_table("webhook_events")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_lead_id"))

    op.drop_table("messages")
    with op.batch_alter_table("followups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_followups_status"))
        batch_op.drop_index(batch_op.f("ix_followups_lead_id"))
        batch_op.drop_index(batch_op.f("ix_followups_due_at"))

    op.drop_table("followups")
    with op.batch_alter_table("email_drafts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_drafts_status"))
        batch_op.drop_index(batch_op.f("ix_email_drafts_lead_id"))
        batch_op.drop_index(batch_op.f("ix_email_drafts_campaign_id"))

    op.drop_table("email_drafts")
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_status"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_lead_id"))

    op.drop_table("workflow_runs")
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_meetings_status"))
        batch_op.drop_index(batch_op.f("ix_meetings_start_at"))
        batch_op.drop_index(batch_op.f("ix_meetings_lead_id"))

    op.drop_table("meetings")
    op.drop_table("campaign_leads")
    op.drop_table("workspace_settings")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_available_at"))

    op.drop_table("jobs")
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaigns_status"))

    op.drop_table("campaigns")
    op.drop_table("activities")
    # ### end Alembic commands ###
