"""business discovery orchestrator

Revision ID: e762444138a9
Revises: 003
Create Date: 2026-10-10 02:09:53.564455

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e762444138a9"
down_revision: str | None = "003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_runs",
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("stage", sa.String(length=60), nullable=False),
        sa.Column("provider_run_id", sa.String(length=100), nullable=True),
        sa.Column("dataset_id", sa.String(length=100), nullable=True),
        sa.Column("provider_cost", sa.Float(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("processed", sa.Integer(), nullable=False),
        sa.Column("ai_calls", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("discovery_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_discovery_runs_status"), ["status"], unique=False)

    op.create_table(
        "prospects",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=False),
        sa.Column("website", sa.String(length=2000), nullable=True),
        sa.Column("country", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("stage", sa.String(length=60), nullable=False),
        sa.Column("emails", sa.JSON(), nullable=False),
        sa.Column("app_status", sa.String(length=40), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("analysis", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["discovery_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "source_key", name="uq_prospect_run_source"),
    )
    with op.batch_alter_table("prospects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prospects_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_prospects_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prospects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prospects_status"))
        batch_op.drop_index(batch_op.f("ix_prospects_run_id"))

    op.drop_table("prospects")
    with op.batch_alter_table("discovery_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discovery_runs_status"))

    op.drop_table("discovery_runs")
    # ### end Alembic commands ###
